version: "3.8"
services:
  nginx:
    container_name: app_nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
      - ./_docker/nginx/ssl:/etc/nginx/ssl
      - ./_docker/nginx/logs:/var/log/nginx/
  nuxt:
    container_name: app_nuxt
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    ports:
      - "3000:3000"
