#import "./types/markType.gql"
#import "./types/folderType.gql"
#import "./types/generationOfferType.gql"
#import "./types/gearboxType.gql"
#import "./types/engineTypeType.gql"
#import "./types/driveTypeType.gql"
#import "./types/bodyTypeType.gql"
#import "./types/ownerType.gql"
#import "./types/imageThumbType.gql"
#import "./types/dealerMiniType.gql"
#import "./types/ColorType.gql"

fragment OfferPagination on OfferTypePagination {
  data {
    id
    external_id
    external_unique_id
    name
    category_enum
    price
    run
    color {
      ... ColorType
    }
    rating {
      rating_total
      rating_body
      rating_interior
      rating_technical
    }
    year
    engine_power
    engine_volume
    mark {
      ... MarkType
    }
    folder {
      ... FolderType
    }
    images {
      ... ImageThumbType
    }
    owner {
      ... OwnerType
    }
    driveType {
      ... DriveTypeType
    }
    bodyType {
      ... BodyTypeType
    }
    gearbox {
      ... GearboxType
    }
    engineType {
      ... EngineTypeType
    }
    generation {
      ... GenerationOfferType
    }
    dealer {
      ... DealerMiniType
    }
  }
  last_page
  total
}
