query articlesPaginate($site_id: Int,  $category_url :String, $page: Int, $limit: Int) {
    articlesPaginate(
        site_id: $site_id,
        category_url: $category_url,
        page: $page
        limit: $limit
    ) {
        data
        {
            id
            slug
            page_title
            url
            views
            body
            createdAt(format:"d.m.Y")
            image{
                medium
                large
                medium_webp
                large_webp
            }

        }
    }
}