#import "./markFieldType.gql"
#import "./folderFieldType.gql"
#import "./generationFieldType.gql"
#import "./gearboxFieldType.gql"
#import "./engineTypeFieldType.gql"
#import "./driveTypeFieldType.gql"
#import "./bodyTypeFieldType.gql"
#import "./ownerFieldType.gql"
fragment ChosenFieldType on ChosenFieldType {
  mark{
    ... MarkFieldType
  }
  folder{
    ... FolderFieldType
  }
  generation{
    ... GenerationFieldType
  }
  gearbox{
    ... GearboxFieldType
  }
  engineType{
    ... EngineTypeFieldType
  }
  driveType{
    ... DriveTypeFieldType
  }
  bodyType{
    ... BodyTypeFieldType
  }
  owner{
    ... OwnerFieldType
  }
  yearFrom
  yearTo
  priceFrom
  priceTo
}
