query offerFilters(
    $site_id: Int,
    $page: Int,
    $limit: Int,
    $category: String,
    $mark_slug_array: [String],
    $folder_slug_array: [String],
    $sort: String,
    $generation_slug_array: [String],
    $engine_type_id_array: [Int],
    $gearbox_id_array: [Int],
    $gearbox_id: Int,
    $body_type_id: Int,
    $drive_type_id_array: [Int],
    $owner_id: Int,
    $year_from: Int,
    $year_to: Int
) {
    offerFilters(
        page: $page,
        limit: $limit,
        site_id: $site_id,
        mark_slug_array: $mark_slug_array,
        folder_slug_array: $folder_slug_array,
        sort: $sort,
        generation_slug_array: $generation_slug_array,
        engine_type_id_array: $engine_type_id_array,
        gearbox_id_array: $gearbox_id_array,
        gearbox_id: $gearbox_id,
        body_type_id: $body_type_id,
        drive_type_id_array: $drive_type_id_array,
        owner_id: $owner_id,
        year_from: $year_from,
        year_to: $year_to,
        category: $category
    )
    {
        mark{
            title
            id
            slug
            folders{
                title
                id
                slug
                generations{
                    title
                    id
                    slug
                }
            }
        }
        bodyType{
            title
            id
            slug
        }
        engineType{
            title
            id
            slug
        }
        driveType{
            title
            id
            slug
        }
        owner{
            title
            id
            slug
        }
        gearbox{
            title
            id
            slug
        }
        year
    }
    offers(
        page: $page,
        limit: $limit,
        site_id: $site_id,
        mark_slug_array: $mark_slug_array,
        folder_slug_array: $folder_slug_array,
        generation_slug_array: $generation_slug_array,
        engine_type_id_array: $engine_type_id_array,
        gearbox_id_array: $gearbox_id_array,
        sort: $sort,
        gearbox_id: $gearbox_id,
        body_type_id: $body_type_id,
        drive_type_id_array: $drive_type_id_array,
        owner_id: $owner_id,
        year_from: $year_from,
        year_to: $year_to,
        category: $category
    ) {
        data {
            id
            name
            price
            run
            year
            engine_power
            engine_volume
            mark {
                id
                slug
                title
            }
            folder {
                id
                slug
                title
            }
            images {
                thumb
                medium
                original
            }
            owner {
                id
                title
                number
            }
            driveType {
                id
                title
                name
            }
            bodyType {
                id
                title
                name
            }
            gearbox {
                id
                title
                name
            }
            engineType {
                id
                title
                name
            }
            external_id
            external_unique_id
            generation {
                id
                slug
                name
            }
        }
        last_page
    }
}
