query usedFolders($site_id: Int!, $mark_id: Int, $mark_slug: String) {
  folders(site_id: $site_id, mark_id: $mark_id, mark_slug: $mark_slug) {
    id,
    title,
    title_rus,
    slug,
    offers_count
  }
}
